{% set name = "pytest-remotedata" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05c08bf638cdd1ed66eb01738a1647c3c714737c3ec3abe009d2c1f793b4bb59

build:
  number: 0
  script: python -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytest >=3.1
    - six

test:
  imports:
    - pytest_remotedata

about:
  home: https://github.com/astropy/pytest-remotedata
  license: BSD
  summary: 'Pytest plugin for controlling remote data access'
  description: |
    This package provides a plugin for the pytest framework that allows
    developers to control unit tests that require access to data from the
    internet.
  doc_url: https://github.com/astropy/pytest-remotedata
  dev_url: https://github.com/astropy/pytest-remotedata

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
