travis:
  secure:
    BINSTAR_TOKEN: RMTCtQWKYmWtLhIPrSkEyigfszZDEmgN9ukJoo+qoIITGgArlGa/joPdhTWjiG+uUbuu/Th6wV0fPpu67de5la7UGrhqgx59m9ro0IRVmlcBlR4q2WXx7SUSmvLrDFgmD4qlLV7w7/USNghz5qp+XL6gHgQyGpG/Jb7y7xAspc2WeXMGeOeIlB2IHKojqN668DwqiUYlnXSo8BdAiH4qqxDq8VLexLuzMxM8JSiiZZyEdpkyFratzVlcASn2ot8icsKgKBCmYsrlQs68ABl/xpZ+SwbVTFEYZsJn45X2cVwT2CKbl1q1O036O/XzZY3NLpv4+GniW8gcwOWrVO3NY8LBT6K61mWK7Z0VPPbRQwjtdXmbGaH9fERBXiJxxdf9sJfvYfja9aXMkK+52AkFnIJgxYJZCX14qkh+LqPxTulFQr/AOCe5/iYanOHry+OREZ7e7qJMf35bLp1LnnW917/gmSs0iRJcVJVSLzwaMklWAJT5ABQKNvWtq/+5s50x6W+Dj7+t/bX1cFm4c/uIPAf8qKgjDc0ElNW0YnRWYGBQf9WjLOa25KRDyJKe4ncyg5B3NshteYz76p6c1yDpuCAQ/k7jOplkKabkY5V/dMAn9LdISRxDnyXXvarNIPe7fhbBbRDZLIA3dCULxp3Mw1BcDAbkNo33wO7xmJXWeqE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
