travis:
  secure:
    BINSTAR_TOKEN: iGEmZwZrnnsDTlcOTWw05wA8SW2PnfJLN8DJ2PfguU33zmilymIEeoOMINB/URTNaAxtmQe6QuzWbv4ErZJy7npZn5A1YPsthNkVdCLbDIZ+3ICC3p/wg8HUngZXcBST84nQ0hNrLNbw7Y8IF4JMFEFYcuczb/92ZlGdt2tAl7ZNhLKy9Zdk3mFTASZMNDHDkZasfWkUiHl+sfDlIXX7Kd8c+ac1MZwG00xB3zMAg82t3JFhjgS742q8Dq2QItGww5lNUsbOlJeDKFU+9b5AFnManUAzR9lEfi5wBMptexb6ey3vQijQD/ucarKMBXC79r45pTwkbKkna4OBl9NHT60s6H7N+V75zlerGbR8snCoIk+RAbqs/jCR8VvGXYTKYDWy7vluAfFucUYNgTppObVAFxIFOTJdqBAtQIJNN6b9pTzC9JdkMuK6FXGem6gM09b4/dMyfa144ojmk2tMvv3jGNbKLvrkJnArSPAfQwXLy8eobK8hFthEv6OKFCycNveTsyVg3gXFgl6eIkMjUbLJdl66MFELF/88QE8cRmZSz8bwh9aWg743Ldf2l8/orZQ8IuTna8EUmdkFFGt0WGGXX6PTJnWPGe5VzTmiw5yfYPp7VVZlqbjFG2Ooua5Xda2dQ7GQece6Vzta9+hS+2FYgSz5t9BtJIRs7TQt+74=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
