travis:
  secure:
    BINSTAR_TOKEN: I5JrDxbgvc64dE0NyUSVT0IpUixwBWv45ox3+pyjIWMNw6GRvW7cPL2W6eXJC1XVgIq4coNQDu/ZSkfG2Vm9V0YjUWmgCRqosuf9o9gDJ80d5UwAt4Li0MppQT3Kthj6yR08ixiF+SlnLDlafIKdxqAcXLqoTgDnECTwssEfytChfw0V95hMICv195EAsOdtBmonjldUSr11HFPte47yusJOGynQGiUxZNX+OWVCsw95vi6oqKoYetFM0nh1+L/oMXuv1fgw19OyKYvbDgw7xzdTyqld7DEDrw4uBT0bHDLuouBQvCK3I2A187js7FUsPdt1xrOT/uCZEynHFloAk+Z/HZdrZAhuNac47UGGtKOkwYnxOdrTW302HVg3NTd90GAp8JHHei4PmAhjgA3+96iFjB9AA5LLylgqejOnDQ3dOiaLVhOmh61nGdaoJdILScq0gXDXe91RjzcSZSHJM/hd5PJSm2L4rM7QZifxZTKPlyo0pob3RyvCgUqx6+3VFP1wSAha/mIfEMu7RaLB8QYeL+/aPRAheBdLkKaq9uTFWpCLikJYM37Rk86jOatm9D/apYKmUzKP1rMMSSUHwR7H1uCjb8pSWNwWSEn34g4+0ibXsA2J7M2U2U84tdM1x6VhZtsnGibKu/9gAnIwoqBAjsQ8LhzInsGTq56IDrE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
